version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000" # Frontend port
      - "3001:3001" # Backend port
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    restart: unless-stopped
